### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by bjanssen** [shaypal5/cachier#1]
I cannot get it to run in Python 2.
The first complaint is about [line 458 in `core.py`](https://github.com/shaypal5/cachier/blob/master/cachier/core.py#L457) (due to)

```
        def func_wrapper(
                *args,
```

I also notices some `super()` calls [[1](https://github.com/shaypal5/cachier/blob/master/cachier/core.py#L84)] [[2](https://github.com/shaypal5/cachier/blob/master/cachier/core.py#L235)], which are only supported in Python 3.

**Comment by shaypal5** [comment]
Hey man!

I'll take a look as soon as I can, and will make it Python 2 compatible if possible (which I think it should; probably only syntax).

I'll update when it's done.
Thanks for taking notice!

**Comment by shaypal5** [comment]
Hey @bjanssen !

I just committed a version working with Python 2.7+! It's even testes and everything!
Thank you for taking the time to open this issue. I hope you enjoy my package.

Cheers,
Shay

**Comment by bjanssen** [comment]
Thanks @shaypal5 !

**Comment by shaypal5** [comment]
Sure thing, @bjanssen .
Please feel free to keep opening issues if you end up using the package and finding bugs, problems or issues requiring improvements.
