### ISSUE TITLE
Annoying MongoDB warning message

### ISSUE THREAD

**Issue by hsolbrig** [shaypal5/cachier#10]
If you don't have pymongo installed, you get the following warning message whenever you use Cachier:

`Cachier warning: pymongo was not found. MongoDB cores will not work.`

There should be some way to turn this off.

**Comment by Kladdkaka** [comment]
+1, lovely little module, but that is really annoying

**Comment by shaypal5** [comment]
Fixed with release [v1.2.5](https://github.com/shaypal5/cachier/releases/tag/v1.2.5).

**Comment by hsolbrig** [comment]
Excellent.  Thanks!!

**Comment by Kladdkaka** [comment]
Thank you very much! ^_^ cheers!
