### ISSUE TITLE
Allow to specify the location of the cache file

### ISSUE THREAD

**Issue by razsteinmetz** [shaypal5/cachier#14]
Allow a way to specify the cache directory

**Comment by boarnasia** [comment]
I agree with you.

For now, this is workaround:

```python
import os
from cachier import cachier, pickle_core

CACHIER_DIR = '/anydir/.cachier'
pickle_core.CACHIER_DIR = CACHIER_DIR
pickle_core.EXPANDED_CACHIER_DIR = os.path.expanduser(pickle_core.CACHIER_DIR)

@cachier()
def foo:
    ...
```

**Comment by shaypal5** [comment]
Added in release `v1.2.8`:
https://github.com/shaypal5/cachier/releases/tag/v1.2.8

**Comment by thluDK** [comment]
Is it possible to set cache_dir globally? It is not clear for me from the documentation.

-Thanks

**Comment by shaypal5** [comment]
Nope. You can only set it per function. 

Global setter and getter function for the general cache directory sounds very useful.
I've opened an issue:
https://github.com/shaypal5/cachier/issues/56
