### ISSUE TITLE
Built-in hash() method is not deterministic, which breaks cachier since #17

### ISSUE THREAD

**Issue by louismartin** [shaypal5/cachier#18]
Cachier is broken for me since #17 for string arguments (probably for other built-in objects as well). 
This comes from the fact that the built-in `hash()` method is not deterministic between runs in python.
Therefore calling it on the arguments of the function for caching purpose does not work between multiple runs because it will hash to different values.

The problematic call to `hash()` is [here](https://github.com/shaypal5/cachier/blob/eb5523ce4caeb1cffc54d3ca281a988519aa8dbb/cachier/pickle_core.py#L182).

# Repro
Run this script twice in a row and it will re-execute the method `test()` each time without relying on the cache:
```
import time
from cachier import cachier

@cachier(pickle_reload=False)
def test(text):
    time.sleep(1)
    print(text)
    print(hash(text))
    return 0

start_time = time.time()
text = 'foo'
print(hash(text))
test(text)
print(time.time() - start_time)
```

**Comment by aleksejkozin** [comment]
@louismartin encountered the same issue yesterday, took me like 5 hours to get that v 1.3.0 broke my code 😄 1.2.8 works fine

Hope it will be fixed

Here is a github action that reproduces the issue
https://github.com/flowbrew/cachier-1.3.0-bug/blob/master/.github/workflows/main.yaml

Here is the github action run logs
https://github.com/flowbrew/cachier-1.3.0-bug/runs/431907332?check_suite_focus=true

**Comment by louismartin** [comment]
It took me a few hours to narrow it down to the hash function as well :)

**Comment by shaypal5** [comment]
On it. I've added a test that reproduces this on my machine. I now want to make I reproduce this on every Travis test configuration, and then I can move forward with test cross-kernel stable hash functions.

**Comment by shaypal5** [comment]
Done. Now let's see if `zlib.adler32()` will solve this, as suggested here:
https://stackoverflow.com/questions/27954892/deterministic-hashing-in-python-3

**Comment by shaypal5** [comment]
Should be solved by release v1.3.3.
Please check and let me know how it goes; you should definitely reopen this issue if this doesn't fix the issue.

**Comment by louismartin** [comment]
Thanks for fixing this so quickly!

**Comment by shaypal5** [comment]
Sure thing! Any pickle-able object should now be a valid argument to a cache-wrapper function - with special treatment given to pandas DataFrames  and numpy arrays - so feel free to try things out.
