### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by tburette** [shaypal5/cachier#2]
Hello,

It doesn't work on Windows due to lack of fcntln :

    
    pip install cachier
    
    In [1]: from cachier import cache
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-4d9fcdd09a5c> in <module>()
    ----> 1 from cachier import cache
    
    c:\users\x\appdata\local\programs\python\python35\lib\site-packages\cachier\__init__.py in <module>()
    ----> 1 from .core import cachier
          2 from ._version import get_versions
          3 __version__ = get_versions()['version']
          4 del get_versions
    
    c:\users\x\appdata\local\programs\python\python35\lib\site-packages\cachier\core.py in <module>()
         26     from concurrent.futures import ThreadPoolExecutor
         27 import time   # to sleep when waiting on Mongo cache
    ---> 28 import fcntl  # to lock on pickle cache IO
         29
         30 import pymongo
    
    ImportError: No module named 'fcntl'

If you opt not to fix it you should mention it in the README and setup files

**Comment by shaypal5** [comment]
Hey @tburette,

You are completely right! I wasn't aware of the problem. :)
I'll mention the incompatibility in the readme, and see if I can find a quick fix.

Thank you for letting me know. I will update you on developments.

Cheers,
Shay

**Comment by faureka** [comment]
Hey @shaypal5 

portalocker is a substitute of fcntl which works a compat module for file locking for both POSIX and windows system. Can we try using that?

**Comment by shaypal5** [comment]
Sure, why not? :)

**Comment by shaypal5** [comment]
I should add, though, that we should first up test coverage to 100%,  and specifically test the scenarios that use file locking.

**Comment by shaypal5** [comment]
@tburette @faureka 

Hey guys,

I finished incorporating portalocker (after upping test coverage to 95%) - thanks to @faureka for the excellent suggestion - and the package should now work on Windows.

Version 1.2.1 is the first released with Windows support. Please try it out if you can.
If and when you report back I can close this issue...

Cheers!

**Comment by tburette** [comment]
I performed a quick test of cachier 1.2.1 on Windows and it now works.

**Comment by shaypal5** [comment]
@tburette 

Thanks, Thomas!
