### ISSUE TITLE
Accessing the cached data from another code ( file )

### ISSUE THREAD

**Issue by Shanki1** [shaypal5/cachier#31]
Hey 

great work you have put in . lovely effort.
i was just checking if it fits for me 

so i had query that ( since it create a pickle file )

if i use the caching from one file or code so the cached folder and files are created.

is there a way to use that cached data from another file or code ?
for example : a flask script to update the cache and another one to execute the needful by reading the values from the cached folder.

thank you

**Comment by shaypal5** [comment]
Hey @Shanki1 

No, not really. It is really not what this package is meant to do.
If the two scripts use the exact same function that appears in the same structure of modules, I think that it might work, but I won't commit to that, and besides, I think there are simpler ways to do what you're trying to achieve.
