### ISSUE TITLE
Cannot pickle over 4GB

### ISSUE THREAD

**Issue by jmrichardson** [shaypal5/cachier#32]
Hi, Great package, finally found this one that I was able to use for my purposes.  I am running into an issue using 3.7 python and pickle not being able to save over 4GB.  I have forked and updated line 139 of pickle_core.py to use protocol 4:

      pickle.dump(cache, cache_file, protocol=4)

However, I am not sure if earlier version of python would accept this hard coded protocol which is why I didn't do a PR.  I am wondering if you could update your package to include this somehow?

Thanks again for for cachier :)

**Comment by shaypal5** [comment]
Hey @jmrichardson ,

Why don't you create a PR with this change, and we will see how it works on all environments and versions on the Travis CI job that will run? :)

Then we can figure out how to condition the pickle protocol on Python version and/or file size.

**Comment by shaypal5** [comment]
Solved with release `v1.4.3` of changes in PR #33 .

**Comment by shaypal5** [comment]
Thank you @jmrichardson !
