### ISSUE TITLE
Deadlock when using MongoDB as a backend

### ISSUE THREAD

**Issue by non-senses** [shaypal5/cachier#37]
**Issue:**

In certain cases the MongoDB backend might leave a deadlock behind, blocking all subsequent requests from being processed.

**Explanation:**

In https://github.com/shaypal5/cachier/blob/17d1b7cc9c57dabb0c40bf7ef748bd68d4a3628c/cachier/core.py#L64 :+1: 

```
def _calc_entry(core, key, func, args, kwds):
    try:
        core.mark_entry_being_calculated(key)
        # _get_executor().submit(core.mark_entry_being_calculated, key)
        func_res = func(*args, **kwds)
        core.set_entry(key, func_res)
        # _get_executor().submit(core.set_entry, key, func_res)
        return func_res
    finally:
        core.mark_entry_not_calculated(key)
```

The happy path procedure is:

1. Mark the entry as being calculated
2. Call the decorated function
3a. If no exception has been thrown, set the result in cache.
3b. If an exception has been thrown, cleanup the entry in the cache.

The buggy path:
1. Mark the entry as being calculated
2. Call the decorated function. 
3. While running the decorated function any major issue occurs. Imagine losing MongoDB connection or the service being stopped with Ctrl-C or Ctrl-D.
4. Restart the service again, call the decorated function again.
5. The entry still exists in DB (because `core.mark_entry_not_calculated(key)` was never called); resulting in an infinite loop in [this line](https://github.com/shaypal5/cachier/blob/master/cachier/mongo_core.py#L135).

```
    def wait_on_entry_calc(self, key):
        while True:
            time.sleep(MONGO_SLEEP_DURATION_IN_SEC)
            key, entry = self.get_entry_by_key(key)
            if entry is None:
                raise RecalculationNeeded()
            if entry is not None and not entry['being_calculated']:
                return entry['value']
```

**Possible solutions**:
1. Avoid creating the lock to begin with; which will make calls to the decorated function to pile up.
2. Set a timeout so the code will loop for a specific period of time, after which it will assume the lock is a deadlock and proceed to call the decorated function. This approach [has been submitted in a PR.](https://github.com/shaypal5/cachier/pull/36)

Please don't hesitate in reaching out if you need more clarifications or some modifications in the PR.

Thanks

Nic

**Comment by shaypal5** [comment]
Hey Nic,

This seems like a good point.

Would you consider writing a PR to fix this? :)

Cheers,
Shay

**Comment by shaypal5** [comment]
Oops. I just recalled that you've opened a PR.  :)

**Comment by shaypal5** [comment]
Solved with #36

**Comment by non-senses** [comment]
Hey @shaypal5 , thanks for merging the PR and closing the issue. Just wanted to update to the latest version in Master but noticed the current Master isn't yet in PIP; the latest release is 1.4.3 from ~September.

Not sure if this is expected as I'm not familiar with the PIP flow for releases tho, so feel free to disregard this message if not applicable. 

Thanks!

**Comment by shaypal5** [comment]
Nope, just had a busy night and forgot to publish to PyPI right away... :)

Up on PyPI version `v1.4.4`.
