### ISSUE TITLE
Is there a way to disable the caching for unit-testing of the client code?

### ISSUE THREAD

**Issue by nima** [shaypal5/cachier#44]
The pickling conflicts with the mock objects otherwise, and it seems like a clean solution could be to have a way to globally disarm all caching.

Since no one else has brought this question up, I assume there's a better way to work around this that I'm unaware of.

**Comment by shaypal5** [comment]
Hey,

I'm not sure I'm following you.
Couldn't you just remove the `@cachier` decorator and test the code?

**Comment by nima** [comment]
Hi!

But that decorator has been used several dozen times throughout the code. I'll see if I can mock it do become a simple pass-through, maybe that will work.

I'll report back on how that goes.

**Comment by nima** [comment]
Okay, fixed, and without having to change very much at all.  Just wanted to share this before I close the ticket.

Right at the top of the test file (that is testing the client-to-cachier code, not cachier itself), the following can be added:
```py
import cachier
dontcachier = lambda *args, **kwargs: lambda fn: fn
unittest.mock.patch(target='cachier.cachier', new=dontcachier).start()
```

Since decorators are called at import-time, and not at call-time, this needs to be done before any other imports that decorate using `cachier.cachier`.

Unrelated, but useful, if cashier is being used to cache API calls to external endpoints, is to block out socket.

```py
import socket
def suckit(*args, **kwargs):
    raise Exception("Nice try, but no Interwebz for you!")
socket.socket = suckit

**Comment by shaypal5** [comment]
Nice!

**Comment by cpatrickalves** [comment]
@shaypal5 
Is there any simple way to change the default value of `ignore_cache` to True instead of False?
In my case, I will use cache only during tests, to cache some API results. 

The @nima solution may work but it would be simple to change the default value of `ignore_cache` to True

**Comment by shaypal5** [comment]
No. If you'd like to contribute a code adding this, I would use something like what I did for my `pdpipe` package:
https://github.com/pdpipe/pdpipe#configuration

This supports both environment variable-driven configuration and config file driven configuration. It is achieved using my `birch` package:
https://github.com/shaypal5/birch

I would add a `cfg.py` file to `cachier` very similar to the one in `pdpipe` (but with properly named config keys):
https://github.com/pdpipe/pdpipe/blob/master/pdpipe/cfg.py

Then, a flag like `IGNORE_CACHE_BY_DEFAULT` can be imported for it, and used to set `ignore_cache`, if it was set.

**Comment by shaypal5** [comment]
Ok, turns out this is already in cachier;
https://github.com/shaypal5/cachier/blob/8943247955404729f4bc19f6f7d1a50fdcddc998/tests/test_mongo_core.py

I would move this to `cachier/cfg.py` and have the `test_mongo_core.py` import the existing keys in the depends on from there, and then add the additional functionality.
