### ISSUE TITLE
Does it support sharing cache files between different processes

### ISSUE THREAD

**Issue by shaoyucheng** [shaypal5/cachier#48]
for example, run a python script multiple times, and i want the same function with same arguments could read from cache instead of calc again.

**Comment by shaypal5** [comment]
Yup, that's the whole point.

**Comment by shaoyucheng** [comment]
Thanks for your reply,  I thought i have asked a silly question. cause i used cachier directly in my business code and i found it not working. then i set up some test codes to verify, it worked well as expected. finally i found the key point was my business code was running through importlib  module and the underlying framework codes generated a uuid for every module imported at every running time which disturbed the unique module name obtained by cachier.  so it's a point worthy of attention if your running mechanism is similar with mine.

**Comment by shaypal5** [comment]
No question is a silly question! And yours proves this point.

I never considered it. I'm guessing there's a way to systematically address this in cache file naming.
