### ISSUE TITLE
Add "In Memory" cache backend.

### ISSUE THREAD

**Issue by techdragon** [shaypal5/cachier#6]
This looks like a solid cache tool, but lack of an in memory backend to both avoid filesystem interaction and not require an external dependency like running mongodb, is a pretty big hinderance for me.

**Comment by shaypal5** [comment]
@techdragon `cachier` is meant to provide persistent cache - as in persistent over different sessions, kernel and even machines - so I naturally thought in-memory storage is not relevant for this.

Couldn't you just use Python's built-in `functools.lru_cache` for fast in-memory caching?
Or are you thinking about Python processes that live for a long time - weeks or months - like servers, for which you want to cache the return values of different functions for different periods of time, so `cachier`'s `stale_after` functionality is what you're missing in Python's `lru_cache`?

**Comment by shaypal5** [comment]
@techdragon Anyway, is should be the easiest core yet to implement, so I can try and find time for this soon, if you think it will be usefull for you.

**Comment by shaypal5** [comment]
Noted. Do you happen to have the time to implement such a component? :)

**Comment by shaypal5** [comment]
Again, due to the package design, this should be pretty simple; you only need to implement an in-memory core, using the structure of the pickle or MongoDB cores as a template, and simply having some in-memory data structure (probably a dictionary).

**Comment by cthoyt** [comment]
@shaypal5 I also have the same interest - would you be willing to accept a PR for this?

**Comment by shaypal5** [comment]
Willing? I would be delighted! 

I saw your PR regarding the `backend` keyword, so I'll tell you what:

I think this should be an API breaking change that will warrant version 2.0.

Let's come up with a generalized scheme on how cores should get their kwargs - it should be streamlined, and not have the decorator itself changing its constructor signature on every change in a core keyword. Adding `**kwargs` and having cores looking there is definitely an option.

This will also bring us one step closer to multi core functionality, have a series of cores ordered linearly, having cache calls cascading fro memory to pickle to mongo, for example.

**Comment by shaypal5** [comment]
Released in `v1.5.0` !!! 🥇 🥳

Congrats and great work, @cthoyt ! First major outside contribution to this project!
I'm so proud. May it be the first of many (by you and/or users of the package)!
