### ISSUE TITLE
Using cachier with network exceptions?

### ISSUE THREAD

**Issue by reagle** [shaypal5/cachier#65]
Hi, thanks for the great package! I'm using cachier to cache calls to Reddit and Pushshift, and sometimes there's a networked based exception. Perhaps I get rate limited or there's something else.

1. I try to include reasonable time.sleep(N) in my queries, but if I'm pulling from cache, there's no need for that. Any suggestions for how to rate limit only if it's not in cache?
2. How often does cachier save it's state? If I get an uncaught network exception on a long data pull, are all the previous cached queries lost?

**Comment by reagle** [comment]
> 1. I try to include reasonable time.sleep(N) in my queries, but if I'm pulling from cache, there's no need for that. Any suggestions for how to rate limit only if it's not in cache?

To answer my own question, I should put the sleeps in the function itself (rather than prior to calling the function); that way they aren't invoked if there's a cache hit.

**Comment by shaypal5** [comment]
Every completed cache call get saved into persistent cache (I'm guess pickle, in your case). :)
