### ISSUE TITLE
Bug?: PickleCore hangs on wait_on_entry_calc

### ISSUE THREAD

**Issue by ErikBrendel** [shaypal5/cachier#82]
My program is hanging on `_PickleCore::wait_on_entry_calc`, because the entry states that the value is currently being calculated. `entry['time']` is two days ago. I am fairly sure that no process is currently calculating this value. The calculation probably started two days ago, and then I aborted the program, so now I suspect that cachier left an inconsistent state behind.

In such cases, it might be helpful to either use `wait_for_calc_timeout` for the pickle core as well, or have an extra option like `max_calc_timeout` that checks the age of the entry allegedly still being calculated (in my case about 48 hours) and triggers re-calculation if this age is above that threshold.

Additional info:
I am running cachier `1.5.3` on linux, using the decorator `@cachier(separate_files=True)` on my function, which is called from different `multiprocessing` processes.

**Comment by shaypal5** [comment]
Ok. 

First, regarding an easy fix, perhaps calling `your_function.clear_cache()` can fix the current state? If you can afford losing the entire cache for this function, I'll suggest you try this and update me.

Second, I wonder if this is related specifically to `separate_files=True` or not. Let's tag @erap129 , who wrote this feature, and see if the thinks it can be related.

Third, please open a separate issue - a feature request - for the `max_calc_timeout` idea. It sounds like a valid idea, but I want to separate the bug report - which my be resolved without adding this feature - and this feature, which *might* turn out to be the only solution we find for this, and might *not*; also, it might be worthwhile regardless of the bug.

Thank you so much for reporting this! :)

Other than that, I'd love to hear what you've been using the package for, and how was your experience so far? Was the bug super early on in your usage of the package and so your experience so far is just *"it break!"*, or did you get actual use out of the package?

Cheers, :)
Shay

**Comment by erap129** [comment]
Yeah I was able to reproduce this behaviour with this code:  
```
from cachier import cachier
import time


@cachier(separate_files=False)
def some_long_function(input):
    time.sleep(10)
    return 1


if __name__ == '__main__':
    print(some_long_function(1))
```

You just have to put a breakpoint here: https://github.com/shaypal5/cachier/blob/51032747f72d48586c66971a1f53972a93c6c603/cachier/core.py#L69
and close the program when the function is being run (you have 10 seconds... :) ) it happens regardless of the value in `separate_files`.   
I think what @ErikBrendel proposed seems reasonable, specifically that `wait_on_entry_calc` will affect the pickle core as well as the mongo core (then we can maybe write this logic in [core.py](https://github.com/shaypal5/cachier/blob/master/cachier/core.py). Would be happy to fix this issue, tell me if you think this approach is good.

**Comment by ErikBrendel** [comment]
Thank you all for the helpful replies!

I fixed it by debugging, finding the cache key of the broken entry, and deleting this file only, so I was able to keep the other cached results. Running my program again, it then correctly started the calculation, stored the result, and everything seems to work again.

I opened the separate issue here: #83 

------

I really liked using this package so far :+1: I am doing a lot of data crawling / processing for my thesis at the moment, and simply attaching `@cachier()` to some methods in the script is easy and helps a lot. Especially when working on the resulting Matplotlib diagrams (which naturally involves a lot of trial and error until it looks nice), having all the final-result-getting-methods cached and being able to regenerate diagrams in a few seconds instead of re-running the whole analysis over-night makes a big difference :)

**Comment by shaypal5** [comment]
Hey Eric. 

I'm closing this issue as I think this should now be taken care of by the added functionality in `v1.5.4`.

Let me know if it does not, or if there are other issues, and feel free to re-open this issue if the problem persists, or other issues, if that's more appropriate.
