### ISSUE TITLE
Add a timeout for "waiting for running calculation" 

### ISSUE THREAD

**Issue by ErikBrendel** [shaypal5/cachier#83]
It can apparently happen that the pickle core leaves an inconsistent state behind (stating that an entry is currently being calculated, which is no longer true), when the calculating process crashes or is aborted by the user. Similar scenarios could probably occur with other persistence cores as well.

It might be helpful to either use `wait_for_calc_timeout` for the pickle core as well, or have an extra option like `max_calc_timeout` that checks the age of a cache entry allegedly still being calculated and triggers re-calculation if this age is above that threshold. It might be reasonable to specify a high default value for this (like 24 hours), or maybe to keep this feature disabled by default to not cause confusion for new users.

In situations where this new timeout was reached (e.g. a method really takes 26 hours to calculate its value, and after 25 hours it was called again, so now there are two processes calculating on the same input), it can happen that the decorated method is calculating result values for the same input multiple times. To keep the results of the cache consistent, I would suggest that whichever invocation finishes first should store its result, and all the others should detect the existing result, discard their own calculation result, and return the cached value. Ideally, if the decorated function is pure, the results should not differ. But if they can differ (e.g. some randomized process is being used, or some time information is incorporated into the result), consistency might be more important.

To reproduce the problem: https://github.com/shaypal5/cachier/issues/82#issuecomment-968334184

See #82 for more info

**Comment by erap129** [comment]
@shaypal5 Gimme the green light and I'm on it... :) Again, I think by using the `wait_for_calc_timeout` for the pickle core as well, as @ErikBrendel suggested.

**Comment by shaypal5** [comment]
Sounds good. Go for it! :)

**Comment by erap129** [comment]
See https://github.com/shaypal5/cachier/pull/84

**Comment by shaypal5** [comment]
Released in `v1.5.4`. :)
