### ISSUE TITLE
CACHIER_MAX_WORKERS environmental variable should appear in the documentation

### ISSUE THREAD

**Issue by sscarduzio** [shaypal5/cachier#89]
I'm using Cachier to limit calls to an external API that limits not only calls/minute, but also has a **maximum concurrent calls** limit (max 5 API calls at the same time).

When using Cachier with `next_time=True`, the stale result is returned, but a thread is spawned to "calculate" the fresher result. In my case, the "calculation" is an API call.

So in order to respect the max 5 parallel API calls limitation, I had to set the environmental variable:

```
CACHIER_MAX_WORKERS=5
```

All good, problem solved, but I had to dig into the Cachier code to find this setting (which I find very important and useful to control concurrency).

I propose to add a line to the README.md about it, or even better, expose a configuration object for Cachier somewhere, so we can set it programmatically.

**Comment by shaypal5** [comment]
Right you are! No excuse!

Closed with https://github.com/shaypal5/cachier/commit/dfb78cff392554d6ebe48957c54546d769e0b769
