### ISSUE TITLE
Is cachier process safe?

### ISSUE THREAD

**Issue by qiuwei** [shaypal5/cachier#96]
We have multiple processes calling the same function with the same arguments almost simultaneously.
If process A and process B both cannot find a valid cache, thus deciding to save the cache onto disk, could the cache be somehow corrupted?

Is saving the cache on to disk atomic?

**Comment by shaypal5** [comment]
Yes, Cachier should be process-safe.

Different threads and processes use file-bound locks (different locks for reading and writing) to read and write to/from the cache for a specific function, and thus a process trying to read even almost immediately after a cache write started will have to wait for the write lock to be released, thus getting an updated version.

In any case, cache corruption shouldn't be an option; worse case should be different versions of the cache in the memory of different processes (each running a distinct Python kernel with a distinct memory space, in which it has its own distinct version of the cache), and possible override of a cached value from one process by that returned from a function call from another.
